---
qualities:
  - name: Original
    params: []
  - name: Photo
    params: ['-resize', '1280x1024']
  - name: Gallery
    params: ['-resize', '800x600']
url:
  host: https://foinq.com
  base: photish-montage
deploy:
  host: foinq.com
  publish_dir: /srv/www/foinq.com/photish-montage
  publish_temp_dir: /tmp/photish-montage-publish
  upload_temp_dir: /tmp/photish-montage-upload
  www_user: www-fqc
